### ISSUE TITLE
image build error

### ISSUE THREAD

**Issue by liupchina** [sonatype-nexus-community/nexus-repository-helm#3]
**as the guide, when i try step Build with Docker,something wrong here. while step Building is ok**

```
Downloaded from rso-public-grid: https://repository.sonatype.org/content/groups/sonatype-public-grid/org/apache/maven/surefire/surefire-junit4/2.20/surefire-junit4-2.20.jar (82 kB at 121 kB/s)
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.sonatype.repository.helm.internal.metadata.ChartIndexTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.013 s - in org.sonatype.repository.helm.internal.metadata.ChartIndexTest
[INFO] Running org.sonatype.repository.helm.internal.metadata.IndexYamlBuilderTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.796 s <<< FAILURE! - in org.sonatype.repository.helm.internal.metadata.IndexYamlBuilderTest
[ERROR] testChartIndexPassedCorrectly(org.sonatype.repository.helm.internal.metadata.IndexYamlBuilderTest)  Time elapsed: 0.036 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
yamlParser.write(
    <any>,
    <Capturing argument>
);
-> at org.sonatype.repository.helm.internal.metadata.IndexYamlBuilderTest.testChartIndexPassedCorrectly(IndexYamlBuilderTest.java:63)
Actually, there were zero interactions with this mock.

	at org.sonatype.repository.helm.internal.metadata.IndexYamlBuilderTest.testChartIndexPassedCorrectly(IndexYamlBuilderTest.java:63)

[INFO] Running org.sonatype.repository.helm.internal.metadata.IndexYamlAbsoluteUrlRewriterTest

[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.305 s - in org.sonatype.repository.helm.internal.security.HelmSecurityFacetTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   IndexYamlBuilderTest.testChartIndexPassedCorrectly:63 
Wanted but not invoked:
yamlParser.write(
    <any>,
    <Capturing argument>
);
-> at org.sonatype.repository.helm.internal.metadata.IndexYamlBuilderTest.testChartIndexPassedCorrectly(IndexYamlBuilderTest.java:63)
Actually, there were zero interactions with this mock.

[INFO] 
[ERROR] Tests run: 18, Failures: 1, Errors: 0, Skipped: 0

```
 
**after exec Building, chang Dockfile "COPY --from=build /nexus-repository-helm/target/nexus-repository-helm-${HELM_VERSION}.jar ${TARGET_DIR}" to "COPY ./target/nexus-repository-helm-${HELM_VERSION}.jar ${TARGET_DIR}",build image succsesful. when i run this image,got another error container logs.**

```
			... 12 common frames omitted
	Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.apache.commons:commons-compress:jar:1.11
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
		at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:705)
		... 12 common frames omitted
2018-09-14 00:38:11,411+0000 INFO  [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender.NexusContextListener - Uptime: 50 seconds and 72 milliseconds
2018-09-14 00:38:11,414+0000 INFO  [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender.NexusLifecycleManager - Stop KERNEL

```
**try this several times,got the same result**

**Comment by papanito** [comment]
Same problem here when running from `mvn clean package`

```
[ERROR] Failures:
[ERROR]   IndexYamlBuilderTest.testChartIndexPassedCorrectly:63
Wanted but not invoked:
yamlParser.write(
    <any>,
    <Capturing argument>
);
-> at org.sonatype.repository.helm.internal.metadata.IndexYamlBuilderTest.testChartIndexPassedCorrectly(IndexYamlBuilderTest.java:63)
Actually, there were zero interactions with this mock.

[ERROR]   YamlParserTest.testWriteIndexYaml:77 expected:<apiVersion: '1.0'[
entries:
  notmongdb:
  - appVersion: 0.0.1
    created: 2018-08-13T22:05:33.023Z
    description: |-
      NoSQL document-oriented database that stores JSON-like documents with
        dynamic schemas, simplifying the integration of data in content-driven applications.
    digest: '12345'
    icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
    maintainers:
    - name: Bitnami
      email: containers@bitnami.com
    name: notmongdb
    sources:
    - https://github.com/bitnami/bitnami-docker-mongodb
    urls:
    - mongodb-0.5.2.tgz
    version: 1.0.0
  mongodb:
  - appVersion: 0.0.1
    created: 2018-08-13T22:05:33.023Z
    description: |-
      NoSQL document-oriented database that stores JSON-like documents with
        dynamic schemas, simplifying the integration of data in content-driven applications.
    digest: '12345'
    icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
    maintainers:
    - name: Bitnami
      email: containers@bitnami.com
    name: mongodb
    sources:
    - https://github.com/bitnami/bitnami-docker-mongodb
    urls:
    - mongodb-0.5.2.tgz
    version: 0.4.9
  - appVersion: 0.0.2
    created: 2018-08-13T22:05:33.023Z
    description: |-
      NoSQL document-oriented database that stores JSON-like documents with
        dynamic schemas, simplifying the integration of data in content-driven applications.
    digest: '12345'
    icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
    maintainers:
    - name: Bitnami
      email: containers@bitnami.com
    name: mongodb
    sources:
    - https://github.com/bitnami/bitnami-docker-mongodb
    urls:
    - mongodb-0.5.2.tgz
    version: 0.4.8]
> but was:<apiVersion: '1.0'[
entries:
  notmongdb:
  - appVersion: 0.0.1
    created: 2018-08-13T22:05:33.023Z
    description: |-
      NoSQL document-oriented database that stores JSON-like documents with
        dynamic schemas, simplifying the integration of data in content-driven applications.
    digest: '12345'
    icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
    maintainers:
    - name: Bitnami
      email: containers@bitnami.com
    name: notmongdb
    sources:
    - https://github.com/bitnami/bitnami-docker-mongodb
    urls:
    - mongodb-0.5.2.tgz
    version: 1.0.0
  mongodb:
  - appVersion: 0.0.1
    created: 2018-08-13T22:05:33.023Z
    description: |-
      NoSQL document-oriented database that stores JSON-like documents with
        dynamic schemas, simplifying the integration of data in content-driven applications.
    digest: '12345'
    icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
    maintainers:
    - name: Bitnami
      email: containers@bitnami.com
    name: mongodb
    sources:
    - https://github.com/bitnami/bitnami-docker-mongodb
    urls:
    - mongodb-0.5.2.tgz
    version: 0.4.9
  - appVersion: 0.0.2
    created: 2018-08-13T22:05:33.023Z
    description: |-
      NoSQL document-oriented database that stores JSON-like documents with
        dynamic schemas, simplifying the integration of data in content-driven applications.
    digest: '12345'
    icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
    maintainers:
    - name: Bitnami
      email: containers@bitnami.com
    name: mongodb
    sources:
    - https://github.com/bitnami/bitnami-docker-mongodb
    urls:
    - mongodb-0.5.2.tgz
]   version: 0.4.8
>
[INFO]
[ERROR] Tests run: 18, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by bhamail** [comment]
I've also seen the intermittent unit test failure mentioned above in: org.sonatype.repository.helm.internal.metadata.IndexYamlBuilderTest#testChartIndexPassedCorrectly()

For me, when I rerun the test/build, it seems to pass just fine. Haven't been able to reliably reproduce the failure. I added some additional test validation in this commit: 95a92728dabd075947759a37b127cf71f25f0e75

If anybody has more info about this intermittent failure, please share.

**Comment by mlukaretkyi** [comment]
Will not be relevant after migrating source code to nexus
